import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";
import { ApolloWrapper } from "~/lib/ apollo-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Toaster
          position="bottom-right"
          toastOptions={{
            duration: 2000,
          }}
        />
        <TRPCReactProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
